name: Integration tests

on:
  # Kör integ-tester på alla PR mot main
  pull_request:
    branches:
    - main 
  # Kör integ-tester även vid push till main
  push:
    branches:
    - main 

jobs:
  integ-test:
    name: integ-test
    runs-on: ubuntu-latest
    env:
      FEATURE_DDB: ${{ secrets.FEATURE_DDB }}
      FEATURE_ADMIN: ${{ secrets.FEATURE_ADMIN }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    steps:

      - name: checkout repo
        # 1) Checka ut koden
        uses: actions/checkout@v4
      - name: install python 3.12
        # 2) Installera rätt Python-version
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install requirment
        # 3) Installera beroenden
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: start localstack
        # 4) Starta localstack
        run: docker compose up -d

      # Stepet väntar på att localstack är redo först 
      - name: Vänta på att LocalStack är redo
        run: |
          until curl -s http://localhost:4566/_localstack/health | grep -E '"dynamodb": *"(available|running)"'; do
            echo "Väntar på LocalStack..."
            sleep 3
          done


      # 5) Initiera DDB-tabeller (infra/local/init.py)
      - name: initiera dynamoDB-tabeler
        run: python infra/local/init.py

      # 6) Kör alla integrationstest
      - name: kör alla integration tester
        run: pytest --no-cov tests/integration

      # 7) Stoppa docker
      - name: stoppa docker
        run: docker compose down
