name: Integration tests

on:
  # TODO: Kör integ-tester på alla PR mot main
  pull_request:
    branches:
    - main 
  # TODO: Kör integ-tester även vid push till main
  push:
    branches:
    - main 

jobs:
  integ-test:
    name: integ-test # Bara ett namn
    runs-on: ubuntu-latest
    env:
      FEATURE_DDB: ${{ secrets.FEATURE_DDB }}
      FEATURE_ADMIN: ${{ secrets.FEATURE_ADMIN }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    steps:

      # TODO: 1) Checka ut koden
      - name: checkout repo
        uses: actions/checkout@v4
      # TODO: 2) Installera rätt Python-version
      - name: install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # TODO: 3) Installera beroenden
      - name: install requirment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      # TODO: 4) Starta localstack
      - name: start localstack
        run: docker compose up -d

      # Stepet väntar på att localstack är redo först 
      - name: Vänta på att LocalStack är redo
        run: |
          until curl -s http://localhost:4566/_localstack/health | grep -E '"dynamodb": *"(available|running)"'; do
            echo "Väntar på LocalStack..."
            sleep 3
          done


      # TODO: 5) Initiera DDB-tabeller (infra/local/init.py)
      - name: initiera dynamoDB-tabeler
        run: python infra/local/init.py

      # TODO: 6) Kör alla integrationstest
      - name: kör alla integration tester
        run: pytest --no-cov tests/integration

      # TODO: 7) Stoppa docker
      - name: stoppa docker
        run: docker compose down
