name: Test & Coverage

on: #triggers on following events
  pull_request:
  push:
    branches: 
      - main #applicable only when pushing to main branch

jobs:
  test:
    name: test # <-- detta namn visas i repo settings
    runs-on: ubuntu-latest
    steps:
      # TODO: 1) Checka ut koden
      - name: Checkout repo  #fetching repo code
        uses: actions/checkout@v4

      # TODO: 2) Installera rätt Python-version
      - name: Install python 3.12
        uses: actions/setup-python@v5
        with: 
          python-version: 3.12

      # TODO: 3) Installera beroenden    
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements-dev.txt;
          pip install -r requirements.txt;

      # TODO: 4) Kör enhetstester med coverage    
      - name: enhetstester
        run: |
          python -m pytest